import type { Locale } from "@/lib/i18n/config";

const copy = {
  en: {
    appName: "Together in Amanah",
    appTagline: "Private clarity before nikah.",
    home: "Home",
    journey: "Journey",
    discuss: "Discuss",
    settings: "Settings",
    welcomeEyebrow: "A private space for two",
    welcomeTitle: "Before the nikah, a conversation.",
    welcomeBody:
      "Answer independently. Compare only when both of you are ready. Your exact answers stay private unless you explicitly share one.",
    welcomePrimary: "Begin together",
    welcomeSecondary: "I have an invite from my partner",
    beginTogether: "Begin together",
    welcomeFooter: "No profiles · No scores · No matchmaking",
    chooseLanguage: "Choose language",
    english: "English",
    french: "Français",
    publicTrust:
      "No public profiles, compatibility scores, or partner-readable private notes.",
    privacyPromise: "Private by default",
    privacyDetail:
      "Your partner sees progress and a neutral comparison—not your exact choice or private note.",
    notAdvice:
      "A guided reflection tool, not religious, legal, medical, or psychological advice.",
    dashboardEyebrow: "Your private journey",
    dashboardTitle: "Make room for honest conversations.",
    dashboardNoSpace: "Begin with a private two-person space.",
    dashboardNoSpaceBody:
      "Create an invite for your partner, or join the space they already created.",
    createSpace: "Create a space",
    joinSpace: "Join a space",
    waitingTitle: "Waiting for your partner",
    waitingBody:
      "Your invite is private, single-use, and expires after seven days.",
    connected: "Connected",
    paused: "Journey paused",
    continueTopic: "Continue your reflection",
    beginTopic: "Begin the first topic",
    topicsProgress: "Topics",
    questionsTogether: "questions ready together",
    unanswered: "Not started",
    inProgress: "In progress",
    yourPartDone: "Your part is done",
    safetyLink: "Feeling unsafe or pressured?",
    safetyEyebrow: "Support",
    safetyTitle: "If something doesn't feel safe",
    safetyIntro:
      "This page is for anyone who feels pressured, controlled, or unsafe, before a marriage or during one. It is general information, not advice about your situation.",
    safetyQuickExit: "Leave this site now",
    safetyQuickExitHint: "Opens a neutral page. You can also press Esc.",
    safetySignsTitle: "Worth taking seriously",
    safetySigns: [
      "Being pressured, threatened, or made to feel guilty about marrying someone, or about staying.",
      "Someone controlling your money, your phone, your documents, or who you are allowed to see.",
      "Feeling afraid of how another person will react to what you say or do.",
      "Being hurt physically or sexually, or being humiliated, isolated, or constantly monitored.",
    ],
    safetyStepsTitle: "What you can do",
    safetySteps: [
      "If you are in immediate danger, contact your local emergency number.",
      "Tell someone you trust. Being believed by one person changes what is possible.",
      "Look for a local support service. Most countries have organisations for domestic abuse and for forced marriage, and many are free and confidential.",
      "Speak to a qualified counsellor, or to a scholar or imam who treats your safety as the priority. A marriage requires consent, and pressure is not consent.",
    ],
    safetyAppNoteTitle: "What this app does and does not do",
    safetyAppNoteBody:
      "This app is not a crisis service and no one monitors it. It never reads your answers to decide what to show you, so it cannot tell whether you are safe. Please do not put abuse, trauma, or medical detail into an answer. Bring it to a person who can help instead.",
    safetyDeviceTitle: "If someone else uses your device",
    safetyDeviceBody:
      "Leaving this page does not erase your browsing history. If that is a risk, open this page in a private or incognito window, and check your browser history and saved passwords when it is safe to do so.",
    waiting: "Waiting for partner",
    ready: "Ready to discuss",
    discussed: "Discussed",
    complete: "Complete",
    yourProgress: "You",
    togetherProgress: "Together",
    topicQuestions: "questions",
    allConversations: "All conversations",
    readyToCompare: "Ready to compare",
    yourTurn: "Your turn",
    answeredWaiting: "Answered · waiting",
    answeredCompareLater: "Answered",
    continueAnswering: "Continue answering",
    topicIntroPrivacy:
      "Answer at your own pace. Your selections and private notes are hidden from your partner.",
    startTopic: "Start this topic",
    continue: "Continue",
    back: "Back",
    questionOf: "Question",
    chooseAnswer: "Choose the answer closest to you",
    importance: "How important is this to you?",
    importanceLow: "Low",
    importanceMedium: "Medium",
    importanceHigh: "High",
    privateNote: "Private note",
    privateNoteHint: "Only you can read this. It is never included in a share.",
    privateNotePlaceholder: "Add context for yourself (optional)",
    saving: "Saving…",
    saved: "Saved privately",
    saveError: "We could not save that. Please try again.",
    previous: "Previous",
    next: "Next",
    finishTopic: "Finish topic",
    answerRequired: "Choose an answer before continuing.",
    savePrivately: "Save privately",
    savedPartnerReady: "Your pattern is ready",
    savedPartnerWaiting: "Saved — your partner hasn’t reached this one yet",
    savedComparisonLater:
      "Saved — you’ll see how this compares once you reach this topic together",
    nextQuestion: "Next question",
    comparisonTitle: "Here’s your pattern.",
    comparisonBody:
      "These results are calculated on the server. Exact answers stay hidden unless their owner shares them.",
    aligned: "Aligned",
    worthDiscussing: "Worth discussing",
    pending: "Waiting for both",
    highPriority: "High importance",
    mattersToOne: "This matters a lot to one of you.",
    mattersToBoth: "This matters a lot to both of you.",
    emptyComparisons: "Nothing is ready yet.",
    emptyComparisonsBody:
      "A comparison appears after both of you answer the same question.",
    openConversation: "Open conversation",
    conversationEyebrow: "Guided conversation",
    yourAnswer: "Your answer",
    partnerAnswer: "Partner answer",
    notShared: "Not shared",
    shareAnswer: "Share my exact answer",
    shared: "Shared",
    shareWarning:
      "Sharing is one-way and permanent for this space. Your private note is never shared.",
    shareConfirmTitle: "Share this exact answer?",
    shareConfirmBody:
      "Your partner will be able to read this option for the rest of this space. Your private note stays private.",
    shareConfirm: "Yes, share my answer",
    cancel: "Cancel",
    starter: "A gentle place to start",
    sharedNotes: "Shared notes",
    sharedNotePlaceholder: "Write only what you both want to keep here",
    addNote: "Add shared note",
    markDiscussed: "Mark as discussed",
    inviteTitle: "Invite your partner",
    inviteBody:
      "Create one private link. Only one other account can use it.",
    inviteCode: "Invite code",
    copyCode: "Copy code",
    copyLink: "Copy link",
    copied: "Copied",
    shareInvite: "Share invite",
    regenerate: "Generate a new code",
    expires: "Expires",
    inviteAgreement:
      "I understand that either person can end this shared space and that exact answers remain private unless explicitly shared.",
    inviteConsentRequired: "Confirm the privacy agreement to continue.",
    joinTitle: "Join your private space",
    joinBody: "Enter the 20-character invite code your partner sent you.",
    joinAction: "Join space",
    inviteUnavailable: "That invite is invalid, expired, or already used.",
    profile: "Profile",
    displayName: "Display name",
    language: "Language",
    save: "Save",
    dataControls: "Data & privacy",
    partnerVisibility: "What your partner can see",
    partnerVisibilityBody:
      "Your partner can see progress counts, comparison patterns, importance signals, shared notes, and answers you explicitly share. They cannot read your other exact answers or any private note. The service has no screen or endpoint that reveals them.",
    export: "Export my record",
    pause: "Pause journey",
    resume: "Resume journey",
    close: "End shared space",
    closeBody:
      "Both people immediately lose access to the shared space. Account deletion also removes the space and all dependent data.",
    closeConfirm: "Type CLOSE to confirm",
    deleteAccount: "Delete account",
    deleteBody:
      "This permanently deletes your account. If you are connected, the shared space is deleted first.",
    summaryTitle: "Your reflection record",
    summaryBody:
      "A private record of your progress, neutral comparisons, discussions, and intentionally shared notes.",
    summaryNotice:
      "This record is not a verdict on compatibility and is not professional or religious advice.",
    noSharedNotes: "No shared notes yet.",
    topicRecord: "Topic record",
    alignmentPatterns: "aligned",
    conversationPatterns: "to discuss",
    partnerPriorities: "are a priority for your partner",
    discussedOn: "Discussed",
    notDiscussedYet: "No discussion recorded yet",
    signOut: "Sign out",
    howEyebrow: "How it works",
    howTitle: "You answer alone. You compare together.",
    demoQuestion: "How involved should family be in everyday decisions?",
    demoOptionOne: "We decide between us first",
    demoOptionTwo: "We ask family for perspective",
    demoOptionThree: "Family is closely involved",
    demoOptionFour: "It depends on the decision",
    partnerCard: "Your partner",
    staysPrivate: "stays private",
    patternWorth: "Pattern: worth a conversation",
    demoCaption:
      "Exact answers are never shown—only where you align and where it is worth talking.",
    continueSetup: "Continue to set up your space",
    sampleAnswerHint: "Tap an option to see how a private comparison works.",
    demoTopics: [
      "Communication",
      "Faith",
      "Family",
      "Home",
      "Roles",
      "Finances",
      "Children",
      "Contract",
      "Health",
      "Conflict",
      "Community",
      "Dealbreakers",
    ],
    pathTitle: "Your path",
    pathNext: "Next",
    pathWaiting: "Your partner is waiting on you for one",
    pathUpToDate: "You’re both up to date",
    recentActivity: "Recent activity",
    eventPartnerJoined: "Your partner joined the space.",
    eventTopicReady: "A conversation pattern is ready.",
    eventSharedNote: "Your partner added a shared note.",
    eventAnswerShared: "Your partner shared an exact answer.",
    unlinkPartner: "Unlink partner and end space",
    pairedWith: "Paired with",
    account: "Account",
    preferences: "Preferences",
    yourSpace: "Your space",
    privacyAndData: "Privacy & data",
    signIn: "Sign in",
    member: "Member",
  },
  fr: {
    appName: "Together in Amanah",
    appTagline: "Une clarté privée avant le nikah.",
    home: "Accueil",
    journey: "Parcours",
    discuss: "Échanger",
    settings: "Réglages",
    welcomeEyebrow: "Un espace privé pour deux",
    welcomeTitle: "Avant le nikah, une conversation.",
    welcomeBody:
      "Répondez séparément. Comparez lorsque vous êtes tous les deux prêts. Vos réponses exactes restent privées sauf si vous choisissez d’en partager une.",
    welcomePrimary: "Commencer ensemble",
    welcomeSecondary: "J’ai une invitation de mon partenaire",
    beginTogether: "Commencer ensemble",
    welcomeFooter: "Aucun profil · Aucun score · Aucun matchmaking",
    chooseLanguage: "Choisir la langue",
    english: "English",
    french: "Français",
    publicTrust:
      "Aucun profil public, score de compatibilité ou note privée lisible par le partenaire.",
    privacyPromise: "Privé par défaut",
    privacyDetail:
      "Votre partenaire voit la progression et une comparaison neutre, jamais votre choix exact ni votre note privée.",
    notAdvice:
      "Un outil de réflexion guidée, et non un avis religieux, juridique, médical ou psychologique.",
    dashboardEyebrow: "Votre parcours privé",
    dashboardTitle: "Faites place aux conversations sincères.",
    dashboardNoSpace: "Commencez par un espace privé pour deux.",
    dashboardNoSpaceBody:
      "Créez une invitation pour votre partenaire ou rejoignez l’espace déjà créé.",
    createSpace: "Créer un espace",
    joinSpace: "Rejoindre un espace",
    waitingTitle: "En attente de votre partenaire",
    waitingBody:
      "Votre invitation est privée, à usage unique et expire après sept jours.",
    connected: "Connectés",
    paused: "Parcours en pause",
    continueTopic: "Poursuivre votre réflexion",
    beginTopic: "Commencer le premier thème",
    topicsProgress: "Thèmes",
    questionsTogether: "questions prêtes à deux",
    unanswered: "Non commencé",
    inProgress: "En cours",
    yourPartDone: "Votre part est terminée",
    safetyLink: "Vous vous sentez en danger ou sous pression ?",
    safetyEyebrow: "Soutien",
    safetyTitle: "Si quelque chose ne vous semble pas sûr",
    safetyIntro:
      "Cette page s'adresse à toute personne qui se sent sous pression, contrôlée ou en danger, avant un mariage ou pendant celui-ci. Il s'agit d'informations générales, pas de conseils sur votre situation.",
    safetyQuickExit: "Quitter ce site maintenant",
    safetyQuickExitHint:
      "Ouvre une page neutre. Vous pouvez aussi appuyer sur Échap.",
    safetySignsTitle: "À prendre au sérieux",
    safetySigns: [
      "Être poussé, menacé ou culpabilisé pour épouser quelqu'un, ou pour rester.",
      "Quelqu'un qui contrôle votre argent, votre téléphone, vos documents ou les personnes que vous pouvez voir.",
      "Avoir peur de la réaction d'une autre personne à ce que vous dites ou faites.",
      "Subir des violences physiques ou sexuelles, ou être humilié, isolé ou surveillé en permanence.",
    ],
    safetyStepsTitle: "Ce que vous pouvez faire",
    safetySteps: [
      "En cas de danger immédiat, contactez le numéro d'urgence local.",
      "Parlez-en à une personne de confiance. Être cru par une seule personne change ce qui devient possible.",
      "Cherchez un service d'aide local. La plupart des pays disposent d'organisations contre les violences conjugales et les mariages forcés, souvent gratuites et confidentielles.",
      "Parlez à un professionnel qualifié, ou à un imam ou un savant qui fait de votre sécurité la priorité. Un mariage exige le consentement, et la pression n'est pas un consentement.",
    ],
    safetyAppNoteTitle: "Ce que cette application fait et ne fait pas",
    safetyAppNoteBody:
      "Cette application n'est pas un service d'urgence et personne ne la surveille. Elle ne lit jamais vos réponses pour décider quoi vous montrer, elle ne peut donc pas savoir si vous êtes en sécurité. N'inscrivez pas de détails sur des violences, un traumatisme ou votre santé dans une réponse. Adressez-vous plutôt à une personne qui peut vous aider.",
    safetyDeviceTitle: "Si quelqu'un d'autre utilise votre appareil",
    safetyDeviceBody:
      "Quitter cette page n'efface pas votre historique de navigation. Si cela représente un risque, ouvrez cette page dans une fenêtre privée, et vérifiez votre historique et vos mots de passe enregistrés lorsque ce sera sans danger.",
    waiting: "En attente du partenaire",
    ready: "Prêt à échanger",
    discussed: "Échangé",
    complete: "Terminé",
    yourProgress: "Vous",
    togetherProgress: "À deux",
    topicQuestions: "questions",
    allConversations: "Toutes les conversations",
    readyToCompare: "Prêt à comparer",
    yourTurn: "À vous",
    answeredWaiting: "Répondu · en attente",
    answeredCompareLater: "Répondu",
    continueAnswering: "Continuer à répondre",
    topicIntroPrivacy:
      "Répondez à votre rythme. Vos choix et notes privées sont cachés à votre partenaire.",
    startTopic: "Commencer ce thème",
    continue: "Continuer",
    back: "Retour",
    questionOf: "Question",
    chooseAnswer: "Choisissez la réponse qui vous ressemble le plus",
    importance: "Quelle importance cela a-t-il pour vous ?",
    importanceLow: "Faible",
    importanceMedium: "Moyenne",
    importanceHigh: "Élevée",
    privateNote: "Note privée",
    privateNoteHint: "Vous seul pouvez la lire. Elle n’est jamais incluse dans un partage.",
    privateNotePlaceholder: "Ajoutez un contexte pour vous-même (facultatif)",
    saving: "Enregistrement…",
    saved: "Enregistré en privé",
    saveError: "Impossible d’enregistrer. Veuillez réessayer.",
    previous: "Précédente",
    next: "Suivante",
    finishTopic: "Terminer le thème",
    answerRequired: "Choisissez une réponse avant de continuer.",
    savePrivately: "Enregistrer en privé",
    savedPartnerReady: "Votre tendance est prête",
    savedPartnerWaiting: "Enregistré — votre partenaire n’a pas encore répondu",
    savedComparisonLater:
      "Enregistré — vous verrez la comparaison lorsque vous arriverez à ce thème ensemble",
    nextQuestion: "Question suivante",
    comparisonTitle: "Voici votre tendance.",
    comparisonBody:
      "Ces résultats sont calculés sur le serveur. Les réponses exactes restent cachées sauf si leur auteur les partage.",
    aligned: "En accord",
    worthDiscussing: "À approfondir",
    pending: "En attente des deux",
    highPriority: "Priorité élevée",
    mattersToOne: "Ce sujet compte beaucoup pour l’un de vous.",
    mattersToBoth: "Ce sujet compte beaucoup pour vous deux.",
    emptyComparisons: "Aucune comparaison prête.",
    emptyComparisonsBody:
      "Une comparaison apparaît lorsque vous avez tous les deux répondu à la même question.",
    openConversation: "Ouvrir la conversation",
    conversationEyebrow: "Conversation guidée",
    yourAnswer: "Votre réponse",
    partnerAnswer: "Réponse du partenaire",
    notShared: "Non partagée",
    shareAnswer: "Partager ma réponse exacte",
    shared: "Partagée",
    shareWarning:
      "Le partage est à sens unique et permanent dans cet espace. Votre note privée n’est jamais partagée.",
    shareConfirmTitle: "Partager cette réponse exacte ?",
    shareConfirmBody:
      "Votre partenaire pourra lire cette option pendant toute la durée de l’espace. Votre note privée reste privée.",
    shareConfirm: "Oui, partager ma réponse",
    cancel: "Annuler",
    starter: "Un point de départ en douceur",
    sharedNotes: "Notes partagées",
    sharedNotePlaceholder: "Écrivez uniquement ce que vous souhaitez garder à deux",
    addNote: "Ajouter la note partagée",
    markDiscussed: "Marquer comme échangé",
    inviteTitle: "Invitez votre partenaire",
    inviteBody:
      "Créez un lien privé. Un seul autre compte peut l’utiliser.",
    inviteCode: "Code d’invitation",
    copyCode: "Copier le code",
    copyLink: "Copier le lien",
    copied: "Copié",
    shareInvite: "Partager l’invitation",
    regenerate: "Générer un nouveau code",
    expires: "Expire le",
    inviteAgreement:
      "Je comprends que chacun peut mettre fin à cet espace et que les réponses exactes restent privées sauf partage explicite.",
    inviteConsentRequired: "Confirmez l’accord de confidentialité pour continuer.",
    joinTitle: "Rejoignez votre espace privé",
    joinBody: "Saisissez le code d’invitation de 20 caractères envoyé par votre partenaire.",
    joinAction: "Rejoindre l’espace",
    inviteUnavailable: "Cette invitation est invalide, expirée ou déjà utilisée.",
    profile: "Profil",
    displayName: "Nom affiché",
    language: "Langue",
    save: "Enregistrer",
    dataControls: "Données et confidentialité",
    partnerVisibility: "Ce que votre partenaire peut voir",
    partnerVisibilityBody:
      "Votre partenaire voit les compteurs de progression, les tendances, les niveaux d’importance, les notes partagées et les réponses que vous partagez explicitement. Il ne peut lire aucune autre réponse exacte ni note privée. Aucun écran ni accès du service ne les révèle.",
    export: "Exporter mon dossier",
    pause: "Mettre le parcours en pause",
    resume: "Reprendre le parcours",
    close: "Mettre fin à l’espace partagé",
    closeBody:
      "Les deux personnes perdent immédiatement l’accès. La suppression d’un compte efface aussi l’espace et ses données.",
    closeConfirm: "Saisissez CLOSE pour confirmer",
    deleteAccount: "Supprimer le compte",
    deleteBody:
      "Cette action supprime définitivement votre compte. Si vous êtes connectés, l’espace partagé est d’abord supprimé.",
    summaryTitle: "Votre dossier de réflexion",
    summaryBody:
      "Un dossier privé de votre progression, des comparaisons neutres, des échanges et des notes volontairement partagées.",
    summaryNotice:
      "Ce dossier n’est pas un verdict de compatibilité ni un avis professionnel ou religieux.",
    noSharedNotes: "Aucune note partagée.",
    topicRecord: "Dossier par thème",
    alignmentPatterns: "en accord",
    conversationPatterns: "à approfondir",
    partnerPriorities: "comptent beaucoup pour votre partenaire",
    discussedOn: "Échangé le",
    notDiscussedYet: "Aucun échange enregistré",
    signOut: "Se déconnecter",
    howEyebrow: "Fonctionnement",
    howTitle: "Vous répondez seul. Vous comparez ensemble.",
    demoQuestion: "Quelle place la famille devrait-elle avoir dans les décisions du quotidien ?",
    demoOptionOne: "Nous décidons d’abord entre nous",
    demoOptionTwo: "Nous demandons l’avis de la famille",
    demoOptionThree: "La famille participe étroitement",
    demoOptionFour: "Cela dépend de la décision",
    partnerCard: "Votre partenaire",
    staysPrivate: "reste privée",
    patternWorth: "Tendance : à approfondir",
    demoCaption:
      "Les réponses exactes ne sont jamais affichées—seulement vos accords et les sujets à approfondir.",
    continueSetup: "Continuer la création de votre espace",
    sampleAnswerHint: "Touchez une option pour voir une comparaison privée.",
    demoTopics: [
      "Communication",
      "Foi",
      "Famille",
      "Foyer",
      "Rôles",
      "Finances",
      "Enfants",
      "Contrat",
      "Santé",
      "Conflit",
      "Communauté",
      "Limites",
    ],
    pathTitle: "Votre parcours",
    pathNext: "À suivre",
    pathWaiting: "Votre partenaire attend votre réponse",
    pathUpToDate: "Vous êtes tous les deux à jour",
    recentActivity: "Activité récente",
    eventPartnerJoined: "Votre partenaire a rejoint l’espace.",
    eventTopicReady: "Une tendance de conversation est prête.",
    eventSharedNote: "Votre partenaire a ajouté une note partagée.",
    eventAnswerShared: "Votre partenaire a partagé une réponse exacte.",
    unlinkPartner: "Dissocier le partenaire et fermer l’espace",
    pairedWith: "Associé à",
    account: "Compte",
    preferences: "Préférences",
    yourSpace: "Votre espace",
    privacyAndData: "Confidentialité et données",
    signIn: "Se connecter",
    member: "Membre",
  },
} as const;

export type V3Copy = (typeof copy)[Locale];

export function getV3Copy(locale: Locale): V3Copy {
  return copy[locale];
}
